new GitGraphWrapper()
    .branch('master')
    .checkout('master')
    .commit()
    .commit()
    .tag('v1.0')
    .branch('develop')
    .checkout('develop')
    .commit('Hello')
    .tag('tag2')
    .commit()
    .checkout('master')
    .commit()
;
