new GitGraphWrapper({orientation: 'vertical-reverse'})
    .branch('master')
    .checkout('master')
    .commit()
    .commit()
    .tag('v1.0')
    .branch('develop')
    .checkout('develop')
    .commit('Hello')
    .tag('tag2')
    .commit()
    .checkout('master')
    .commit()
    .orphanBranch('orphan')
    .checkout('orphan')
    .commit()
    .commit()
    .checkout('develop')
    .commit()
    .checkout('master')
    .merge('develop', {message: 'merge from develop'})
    .merge('orphan')
;
